#!/bin/sh

## This is an example config file
## All configurations done here will be interpreted as a SH script

## Remaining seconds to wait for next OTP
#WAIT_FOR_NEXT=5

## Fix if the current directory can't be found
#CURRENT_DIR=$HOME/otp-cli/

## Disables permissions Warning
#PERMISSION_WARN=0
