#!/bin/sh
CURRENT_DIR=$(dirname `$(command -v realpath || command -v readlink) $0`)
. $CURRENT_DIR/lib/common
CMD=$1
[ $# -gt 0 ] && shift

show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) <command> [-h]"
  echo
  echo " -h : If after a <command>, the respective help. Otherwise, this help."
  echo
  echo " Where <command> are:"
  echo
  echo " help   : This help"
  echo " add    : Add a new token"
  echo " clip   : Copy OTP to clipboard"
  echo " show   : Show the current OTP"
  echo " list   : List available tokens"
  echo " unlock : Unlock an encrypted token"
  echo " remove : Remove a token"
  exit 1
}

case $CMD in
  add)
  ;;
  clip)
  ;;
  remove)
  ;;
  show)
  ;;
  unlock)
  ;;
  list)
  ;;
  help)
  show_usage
  ;;
  -h)
  show_usage
  ;;
  -help)
  show_usage
  ;;
  *)
  show_usage "Unknow command $CMD"
  ;;
esac

. $CURRENT_DIR/lib/$CMD
