#!/bin/sh

TOKEN_NAME=$1
TOKEN_KEY=$2

show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) add [-h] [Token Name] [Token Key]"
  echo
  echo " -h : This help"
  echo
  echo "If [Token Name] or [Token Key] are empty, they will be prompted."
  exit 1
}

if [ "-h" = "$1" ]; then
  show_usage
  exit 1
fi

read_token_name

if [ -z "$TOKEN_KEY" ]; then
  read_hidden_input "Token key: "
  echo
  TOKEN_KEY=$IN
  if [ -z "$TOKEN_KEY" ]; then
    show_usage "Token key can not be empty"
    exit 1
  fi
fi

echo
echo "An empty password will not lock the file"
read_hidden_input "Password: "
echo
PASSWORD1=$IN

create_plain_token

if [ -z "$PASSWORD1" ]; then
  echo "WARN: Token is not password protected!"
  echo "Created [$INPUT_FILE]"
  exit 0
fi

read_hidden_input "Confirm password: "
echo
PASSWORD2=$IN

if [ "$PASSWORD1" != "$PASSWORD2" ]; then
  echo "ERROR: The passwords do not match!"
  exit 1
fi

encrypt_token_to_file
