#!/bin/sh

validate_modifiers()
{
  OUTPUT="/dev/stdout"

  [ "$1" = "-h" ] && show_usage

  while [ $# -gt 0 ]
  do
    [ "$1" = "-k" ] && KEEP="true"
    [ $1 != -* ] && TOKEN_NAME="$1"
    shift
  done
}

show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) clip [-h] [-k] <Token Name>"
  echo
  echo " -h : This help"
  echo " -k : Keep generating OTP."
  exit 1
}

#Init
validate_modifiers $@

read_token_name

get_token

[ $WAIT_FOR_NEXT -gt 0 ] && [ "$KEEP" = "" ] && WAIT=true

while true; do
  remaining_seconds
  X=$( oathtool --totp -b "$TOKEN" )

  copy_to_clipboard $X

  if [ $WAIT ]; then
    [ $WAIT_FOR_NEXT -gt $REMAINING ] && printf "\r[%.2d] (Waiting for next token ...)" $REMAINING
    [ $WAIT_FOR_NEXT -lt $REMAINING ] && break
  fi

  [ "$WAIT" = "" ] && [ "$KEEP" = "" ] && break

  sleep 1
done

echo
