#!/bin/sh

TOKENFILES_DIR="$HOME/otp-cli/tokens"
OS=$( uname )

function check_tokenfiles_dir {
  if [[ ! -a "$TOKENFILES_DIR" ]]; then
    echo "ERROR: Directory $TOKENFILES_DIR can not be created!"
    exit 1
  fi

  check_permissions $TOKENFILES_DIR "700"
}

function set_tokenfiles_dir {
  if [[ ! -a "$TOKENFILES_DIR" ]]; then
    mkdir -p $TOKENFILES_DIR
    chmod 700 $TOKENFILES_DIR
  fi
}

function check_permissions {
  if [[ $OS = "Darwin" ]]; then
    PERMISSIONS=$( stat -L -f "%A" $1 )
  elif [[ $OS = "Linux" ]]; then
    PERMISSIONS=$( stat -L -c "%a" $1 )
  fi

  if [ $PERMISSIONS != $2 ]; then
    echo "Perms on [$1] are too permissive. Try 'chmod $2 $1' first"
    exit 1
  fi
}

set_tokenfiles_dir
check_tokenfiles_dir
