#!/bin/sh
LAST_PASSWORD=0

read_input()
{
  if [ $OS = "OpenBSD" ]; then
    echo -n $1
    read -r IN
  else
    read -r -p "$1" IN
  fi
}

read_hidden_input()
{
  stty -echo
  read_input "$1"
  stty echo
}

check_tokenfiles_dir()
{
  if [ ! -d $TOKENFILES_DIR ]; then
    echo "ERROR: Directory $TOKENFILES_DIR not created!"
    exit 1
  fi

  check_permissions $TOKENFILES_DIR "700"
}

set_tokenfiles_dir()
{
  if [ ! -d "$TOKENFILES_DIR" ]; then
    mkdir -p $TOKENFILES_DIR
    chmod 700 $TOKENFILES_DIR
  fi
}

create_plain_token()
{
  INPUT_FILE="$TOKENFILES_DIR/$TOKEN_NAME"
  echo $TOKEN_KEY > $INPUT_FILE
  chmod 400 $INPUT_FILE
}

check_permissions()
{
  if [ $PERMISSION_WARN -eq 1 ]; then
    if [ $( expr $OS : '.*BSD' ) != "0" ]; then
      PERMISSIONS=$( stat -f "%OLp" $1 )
    elif [ $( stat --version | head -n 1 | grep -c GNU ) = "1" ]; then
      PERMISSIONS=$( stat -L -c "%a" $1 )
    else
      PERMISSIONS=$( stat -L -f "%A" $1 )
    fi

    if [ $PERMISSIONS != $2 ]; then
      echo "WARNING: File permissions on [$1] are too permissive. Use 'chmod $2 $1'"
    fi
  fi
}

get_basename_wo_ext()
{
  if [ $OS = "OpenBSD" ]; then
    BASENAME_WO_EXT=$( basename $1 $2 )
  else
    BASENAME_WO_EXT=$( basename -s $2 $1 )
  fi
}

get_token_file()
{
  TOKEN_PATH=${TOKENFILES_DIR}/${TOKEN_NAME}
  set "${TOKEN_PATH}*" "${TOKEN_PATH}"
  FILES="$@"
  for file in $FILES; do
    if [ -f "${file}" ]; then
      check_permissions $file "400"
      TOKEN_FILE="${file}"
      get_basename_wo_ext $file .enc
      [ "$BASENAME_WO_EXT" != "$( basename $file )" ] && ENCRYPTED=1
      get_basename_wo_ext $file .pbkdf2
      [ "$BASENAME_WO_EXT" != "$( basename $file )" ] && ENCRYPTED=2
      return 0
    fi
  done

  echo "ERROR: Token file '$TOKEN_NAME' doesn't exist"
  exit 1
}

decrypt_token_from_file()
{
  read_hidden_input "OTP Password: "
  [ $ENCRYPTED -eq 2 ] && PBKDF2="-pbkdf2 -iter 100000"
  TOKEN=$( echo -n $IN | openssl enc -aes-256-cbc $PBKDF2 -d -salt -pass stdin -in $TOKEN_FILE )
}

encrypt_token_to_file()
{
  INPUT_FILE="$TOKENFILES_DIR/$TOKEN_NAME"
  OUTPUT_FILE="$TOKENFILES_DIR/$TOKEN_NAME.pbkdf2"
  rm -f "$OUTPUT_FILE"
  echo -n $PASSWORD1 | openssl enc -aes-256-cbc -pbkdf2 -iter 100000 -salt -pass stdin -in "$INPUT_FILE" -out "$OUTPUT_FILE"
  rm -f "$INPUT_FILE"
  chmod 400 $OUTPUT_FILE
  echo "Created [$OUTPUT_FILE]"
}

plaintext_token_from_file()
{
  TOKEN=$( cat $TOKEN_FILE )
}

get_token()
{
  get_token_file
  if [ $ENCRYPTED -eq 0 ]; then
    plaintext_token_from_file $TOKEN_FILE
  else
    decrypt_token_from_file $TOKEN_FILE
  fi

  echo "$TOKEN" | grep -Eqv '^[0-9A-Za-z]+$' && exit 1
}

verify_command()
{
  command -v $1 >/dev/null 2>&1 || { echo >&2 "\n\nRequired '$1'. Install it and try again.\nAborting."; exit 1; }
}

copy_to_clipboard()
{
  if [ "$1" != "$LAST_PASSWORD" ]; then
    if [ $OS = "Darwin" ]; then
      verify_command "pbcopy"
      printf "$1" | pbcopy
    elif [ ! -z "$DISPLAY" ]; then
      verify_command "xclip"
      printf "$1" | xclip -sel clip
    else
      printf "$1"
      NO_CLIP=1
    fi
    LAST_PASSWORD="$1"
  fi
}

read_token_name()
{
  if [ -z "$TOKEN_NAME" ]; then
    read_input "Token name: "
    TOKEN_NAME=$IN
    if [ -z "$TOKEN_NAME" ]; then
      show_usage "Token name can not be empty"
      exit 1
    fi
  fi
}

remaining_seconds()
{
  REMAINING=$(( 30 - (`date +%s` % 30) ))
}

get_otp()
{
  OTP=$( oathtool --totp -b "$1" )
}

verify_command "openssl"

set_tokenfiles_dir
check_tokenfiles_dir
