#!/bin/sh

show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) remove [-h] [Token Name]"
  echo
  echo " -h : This help"
  echo
  echo "If [Token Name] is empty, it will be prompted."
  exit 1
}

if [ "$1" = "-h" ]; then
  show_usage
  exit 1
fi

TOKEN_NAME=$1

read_token_name

get_token_file

if [ -f $TOKEN_FILE ]; then
  rm -f $TOKEN_FILE
  echo "Removed file [$TOKEN_FILE]"
fi
