#!/bin/sh

validate_modifiers()
{
  OUTPUT="/dev/stdout"

  [ "$1" = "-h" ] && show_usage

  while [ $# -gt 0 ]
  do
    [ "$1" = "-c" ] && TO_CLIPBOARD=true
    [ "$1" = "-1" ] && ONE_TIME=true
    [ "$1" = "-s" ] && OUTPUT="/dev/null"
    [ $1 != -* ] && TOKEN_NAME="$1"
    shift
  done
}


show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) show [-h] [-1] [-c] [-s] <Token Name>"
  echo
  echo " -h : This help"
  echo " -1 : Get one password and exit."
  echo " -c : Copy to clipboard."
  echo " -s : Silent. Do not output anything to console."
  exit 1
}

#Init
validate_modifiers $@

read_token_name

get_token

echo > $( echo "$OUTPUT" )

[ $ONE_TIME ] && [ $WAIT_FOR_NEXT -gt 0 ] && WAIT=true

process_otp()
{
  get_otp $TOKEN
  [ $TO_CLIPBOARD ] && copy_to_clipboard $OTP
  return 0
}

while true; do
  remaining_seconds
  process_otp

  [ $WAIT ] && [ $WAIT_FOR_NEXT -ge $REMAINING ] && OTP="(Waiting for next token ...)"

  display_message=`printf "[%.2d] $OTP" $REMAINING`

  printf "\r" > $( echo "$OUTPUT" )
  [ $display_message_size ] && for i in `seq $display_message_size`; do printf " " > $( echo "$OUTPUT" ); done
  printf "\r$display_message" > $( echo "$OUTPUT" )

  display_message_size=${#display_message}

  [ $ONE_TIME ] && [ $WAIT_FOR_NEXT -lt $REMAINING ] && process_otp && break

  sleep 1
done

echo
