#!/bin/sh

show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) unlock [-h] [Token Name]"
  echo
  echo " -h : This help"
  echo
  echo "If [Token Name] is empty, it will be prompted."
  exit 1
}

if [ "$1" = "-h" ]; then
  show_usage
  exit 1
fi

TOKEN_NAME=$1

read_token_name

get_token_file

if [ ! -f $TOKEN_FILE ]; then
  echo "The file [$TOKEN_FILE] does not exist"
  exit 1
fi

get_token

[ $ENCRYPTED -eq 0 ] && echo "Already unlocked" && exit 1
[ $ENCRYPTED -eq 1 ] && get_basename_wo_ext $TOKEN_FILE .enc
[ $ENCRYPTED -eq 2 ] && get_basename_wo_ext $TOKEN_FILE .pbkdf2

OUTPUT_FILE=${TOKENFILES_DIR}/$BASENAME_WO_EXT

rm -f $OUTPUT_FILE
echo $TOKEN > $OUTPUT_FILE
chmod 400 $OUTPUT_FILE
rm -f $TOKEN_FILE

echo
echo "Unlocked file [$OUTPUT_FILE]"
