#!/bin/sh

show_usage()
{
  [ -n "$1" ] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) unlock [-h] [Token Name]"
  echo
  echo " -h : This help"
  echo
  echo "If [Token Name] is empty, it will be prompted."
  exit 1
}

if [ "$1" = "-h" ]; then
  show_usage
  exit 1
fi

TOKEN_NAME=$1

read_token_name

ENC_FILE="$TOKENFILES_DIR/$TOKEN_NAME.enc"

if [ ! -f $ENC_FILE ]; then
  echo "The file [$ENC_FILE] does not exist"
  exit 1
fi

get_token

OUTPUT_FILE=$( echo $ENC_FILE | sed 's/.enc//' )

echo $TOKEN > $OUTPUT_FILE
chmod 400 $OUTPUT_FILE
rm -f $ENC_FILE

echo
echo "Unlocked file [$OUTPUT_FILE]"
