#!/bin/sh

function show_usage {
  [[ -n "$1" ]] && echo "ERROR: $1"
  echo "Usage: $( basename ${0} ) unlock [-h] [Token Name]"
  echo
  echo " -h : This help"
  echo
  echo "If [Token Name] is empty, it will be prompted."
  exit 1
}

if [[ "$1" == "-h" ]]; then
  show_usage
  exit 1
fi

TOKEN_NAME=$1

if [[ -z "$TOKEN_NAME" ]]; then
  read -r -p "Token name: " TOKEN_NAME
  if [[ -z "$TOKEN_NAME" ]]; then
    show_usage "Token name can not be empty"
    exit 1
  fi
fi

INPUT_FILE="$TOKENFILES_DIR/$TOKEN_NAME.enc"

if [ ! -f $INPUT_FILE ]; then
  echo "The file [$INPUT_FILE] does not exist"
  exit 1
fi

read -s -r -p "Password to unlock file: " PASSWORD

OUTPUT_FILE=$( echo $INPUT_FILE | sed 's/.enc//' )

echo $PASSWORD | openssl enc -aes-256-cbc -d -salt -in "$INPUT_FILE" -out "$OUTPUT_FILE" -pass stdin

TOKEN=$( cat $OUTPUT_FILE )

if [[ ! $TOKEN =~ ^[0-9A-Z]+$ ]]; then
  echo "ERROR: Can not unlock file!"
  rm $OUTPUT_FILE
  exit 1
fi

echo
echo "Unlocked file [$OUTPUT_FILE]"
